language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.3
    - android-21

notifications:
  slack:
    rooms:
     - douncoding:SzYCoXHcw4rqdoJpY8DZD0ev

script:
  - chmod +x gradlew
  - ./gradlew build
