language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.3
    - android-23

    # Support library
    - extra-android-support
    - extra-android-m2repository

notifications:
  slack:
    rooms:
     - douncoding:SzYCoXHcw4rqdoJpY8DZD0ev

before_install:
 - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
