language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - build-tools-23.0.3
    - android-23

    # Support library
    - extra-android-support
    - extra-android-m2repository

notifications:
  slack:
    rooms:
     - douncoding:SzYCoXHcw4rqdoJpY8DZD0ev

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - chmod +x gradlew
  - ./gradlew build
